### ISSUE TITLE
Unit tests for fairly package

### ISSUE THREAD

**Issue by manuGil** [ITC-CRIB/fairly#8] opened 2022-09-15 05:47 UTC

**Comment by jurra** [comment] 2022-10-04 14:09
Hello @girgink and @manuGil I came across a nice tool for testing called vcr: [https://github.com/kiwicom/pytest-recording](https://github.com/kiwicom/pytest-recording) (This question is mostly for @girgink )

Currently everything is being tested against production servers, but mocking the API is a bit more elegant and efficient than testing directly to zenodo or figshare everytime we run tests.

There are different approaches to do this but I found the vcr approach quite useful as it makes a recording of a server response mock locally automatically and it also gets updated if the API changes.

The problem is that is currently conflicting with the solution we have where we monkeypatch the HTTPConnection block size to improve connection speed (Line 269 in client/__init__.py). I commented the line to test and it worked. It would be nice to dicuss what could be a best way to go about this.

**Comment by girgink** [comment] 2022-10-05 10:24
Hi @jurra, it looks interesting. How does it get updated if the API (e.g. Zenodo, Figshare) gets updated? To be honest I don't see any problem in testing against production servers, as they are the ones the package should work with properly. As far as I know there are also sandbox servers available, so we can use them as well, if necessary.

HTTPConnection block size makes a significant difference in uploading/downloading large files. Unfortunately the patch is not a good way to correct it, but I think currently it is the only way to do that. Are you aware of any other ways?

**Comment by jurra** [comment] 2022-10-05 11:31
Hi @girgink vcr can be updated when the API changes, it is like a local cache if you like of the endpoints you call recorded in yaml, if you delete these files, it will test against the actual production servers again. 

I managed to make it work by the way.

**Comment by jurra** [comment] 2022-10-05 19:40
I am currently working on setting up the CI so that we can run tests on gihtub. Still work in progress.

**Comment by girgink** [comment] 2022-10-06 08:24
> vcr can be updated when the API changes

But this is why we have testing, right? To be able to capture if the API changes or not. VCR doesn't help with this; moreover, it prevents us to find out if API changed or not, so it delay the process. I don't suggest using it, as long as we can use the actual servers or sandboxes for testing.

**Comment by jurra** [comment] 2022-11-01 12:46
Hi everyvody, I am closing this issue as we agreed that VCR doesnt exclude the testing also against the actual API

**Closed by jurra** 2022-11-01 12:46 UTC
Labels: enhancement
